### ISSUE TITLE
[API] `distributions` module should be renamed to `soft_labelling`

### ISSUE THREAD

**Issue by victormvy** [ayrna/dlordinal#39]
`distributions` module do not implement probability distributions. Instead, it employs different probability distributions to determine soft labels for a given number of splits. Therefore, the whole module should be renamed to `softlabelling` and the functions that it contains should also be renamed as follows:
- `get_beta_probabilities` -> `get_beta_softlabels`
- `get_binomial_probabilities` -> `get_binomial_softlabels`
- `get_exponential_probabilities` -> `get_exponential_softlabels`
- `get_triangular_probabilities` -> `get_triangular_softlabels`
- `get_general_triangular_probabilities` -> `get_general_triangular_softlabels`

**Comment by franberchez** [comment]
`distribution` module has been renamed to `soft_labelling`
