### ISSUE TITLE
[API] Standardisation of the interface of the functions of the module distributions

### ISSUE THREAD

**Issue by victormvy** [ayrna/dlordinal#40]
Some functions in the `distributions` module compute the soft labels for a single target (`get_beta_probabilities`) while others compute the soft labels for all `J` classes. Therefore, some functions return a vector while others return a 2d matrix. It should be standardised.

**Comment by victormvy** [comment]
I have updated the `get_beta_softlabels` function as suggested. The unittests still need to be updated.

**Comment by victormvy** [comment]
Tests have also been updated

**Comment by franberchez** [comment]
Thank you again for your contribution!
