### ISSUE TITLE
Avoid default value for `num_classes` parameter in Unimodal Loss Functions

### ISSUE THREAD

**Issue by victormvy** [ayrna/dlordinal#44]
The `num_classes` parameter in unimodal loss functions currently has a default value. However, it's important to note that specifying the correct number of classes for this parameter must be done for every case. Relying on a default value may lead to errors that are difficult to diagnose.

Recommendation:
- Remove the default value for the `num_classes` parameter in `BetaCrossEntropyLoss`, `BinomialCrossEntropyLoss`, `ExponentialRegularisedCrossEntropyLoss`, `GeneralTriangularCrossEntropyLoss`, `PoissonCrossEntropyLoss`, and `TriangularCrossEntropyLoss`

**Comment by franberchez** [comment]
The default value of the parameter ``num_classes`` in unimodal loss functions has been removed, to avoid problems in future user implementations.
